### ISSUE TITLE
USER STORY: Manage User Account

### ISSUE THREAD

**Issue by moolleer** [moolleer/P4-m-nes-restaurant#10]
Epic #8 

As a **site User** I can **log in/out and manage my account** so that **I can manage or delete my profile.**

## Acceptance Criteria:
* A login/logout button should always be visible in the navbar.
* If the user is logged out, a login button should always be visible in the navbar
* When the login button is clicked, the user should be brought to the login page
* If the user enter invalid account details when trying to login, a message should display with information about incorrect details 
* A message should display that the user has been successfully logged in
* If the user clicks on the log out button, a confirmation request should be displayed before proceeding
* A message should display that the user has been logged out successfully

## Tasks:
- [ ] Add login/logout buttons to the navbar
- [ ] Customize the login & logout templates-
- [ ] Create messages to be displayed when user login/logout and for incorrect details.

**Comment by moolleer** [comment]
Future: Customize templates
