### ISSUE TITLE
USER STORY: Manage Booking

### ISSUE THREAD

**Issue by moolleer** [moolleer/P4-m-nes-restaurant#13]
Epic #11 

As a **logged in site User/ Admin** I can manage a booking** so that **I can change or cancel my booking as needed.**

## Acceptance Criteria:
* A site User/Admin can change the time, date or number of people.
* A site User/Admin can delete a booking. 
* Show a message with information of the action to notify the user, and to make them aware that this cannot be undone.

## Tasks:
- [ ] The booking app should allow a site User/Admin to change the time and date for the booked timeslot.
- [ ] The booking app should allow a site User/Admin to to delete the booking.
- [ ] Create messages for changing or deleting a booking.
