### ISSUE TITLE
USER STORY: User Account

### ISSUE THREAD

**Issue by moolleer** [moolleer/P4-m-nes-restaurant#9]
Epic #8 

As a **site User** I can **create an account** so that **I can make, change or delete a booking.**

## Acceptance Criteria:
* A signup button should always be visible when users are not logged in/signed up
* When a site User click the button they should be brought to the sign up form
* When a site user fills in their details and click on the Create Account button a new account should be created.
* A confirmation message shoud appear to notify the user of a successful registration.

## Tasks:
- [ ] Add a signup button to the navbar
- [ ] Use Allauth for authentication
- [ ] Customize a signup form 
- [ ] Create message for registration
